# Generated by Django 2.1.5 on 2019-07-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_review_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
