# Generated by Django 2.2.2 on 2019-07-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='number_of_reviews',
            field=models.IntegerField(default=0),
        ),
    ]
