# Generated by Django 2.2.2 on 2019-08-12 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0009_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='review',
        ),
    ]
