# Generated by Django 2.2.2 on 2019-08-17 15:45

from django.db import migrations, models
import django.db.models.deletion
import shops.models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0010_auto_20190812_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=shops.models.get_image_filename, verbose_name='Image')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.Review')),
            ],
        ),
    ]
